### ISSUE TITLE
Feature: Setup drip cron for populating the supabase

### ISSUE THREAD

**Issue by bdougie** [open-sauced/actions#26]
### Type of feature

🍕 Feature

### Current behavior

The current GitHub Actions runs only on demand because it is very expensive (40 mins+). 

### Suggested solution

Per @0-vortex, we can set this up with a checked.json and perform the check on a limited amount of users per hour. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
.take

**Comment by 0-vortex** [comment]
.take

**Comment by 0-vortex** [comment]
Works 🙌
